#!/bin/bash

if [ $# -ge 3 ]; then
   length=$1
   nums=$2
   spcls=$3
else
   length=8
   nums=2
   spcls=2
fi

if [ $# -eq 1 ]; then
    loop_count=$1
elif [ $# -eq 4 ]; then
    loop_count=$4
else
    loop_count=10
fi

echo
for ((i=1; i<=$loop_count; i++))
do
   java CreatePassWord $length $nums $spcls
done
echo
